### PR TITLE
add read json from form files

### PR DESCRIPTION
**Pull request by stiio**
Needed for clients generated using openapi-generator (#16)

### CODE REVIEW

**Comment by phunanon** [comment]
@Morasiu, when might this be merged?

**Comment by Morasiu** [comment]
I'll try to merge it soon. Just have to test it

**Comment by Morasiu** [comment]
What would a wrapper for this look like? Can you provide an example?


Would it be like this (with usage presented below)?
```csharp
public class JsonAsFileWrapper {
	[FromJson]
	public IFormFile Blob { get; set; }
	
	public IFormFile File { get; set; }
}

```

```csharp
public IActionResult PostWrapper([FromForm] JsonAsFileWrapper wrapper)
```

**Comment by Morasiu** [comment]
@stiio Forgot to mention you:)

**Comment by stiio** [comment]
@Morasiu my code just adds support for reading json's when they are sent as a file.

1. The default sending option.  
image

2. Sending json as a blob. (this is what clients generated using the open api generator do)  
image

**Comment by Morasiu** [comment]
Okay. I see it now. Thanks :D

**Pull request merged**
